version: '3'
networks:
    # red que comparte servicio 
    mysql-java-angular:
      driver: bridge

services:
  bd:
    build: ./bbdd
    container_name: bd 
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "4100:3306" #puerto de conexion dentro de contexto contenedor 3306
    networks:
      - mysql-java-angular
  backend:
    build: ./ServicioUsuario
    container_name: backend
    ports:
      - "4200:8080" # puerto que recibe solicitud de app angular 4200
    depends_on:
      - bd
    networks:
      - mysql-java-angular
  frontend:
    build: ./angular/app-usuarios
    container_name: frontend
    ports:
      - "8082:80"
    depends_on:
      - bd
      - backend
    networks:
      - mysql-java-angular
  